apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAdLkrbkUQ8sD/jPcMiknb98aJdo70inyACTGTS103c9LInzehlgMBygXJnDMNMqOI/uage1BKn+AMbxubpGmIgYK5DM7WSSp7lH6mP48MOR2E2lJkYJcDL1oogLwJQIgs9y+iPXUgqq2LlyIgQOJxCKAO7ap4C1niBtnbfHnHNlqfMlo772riEkOYzuTlpMnkIfT9SPVJ32teZ8fME2WXE8CV8yo/hIqkpbA3JlmRVaLyV4Y9rvoNkWM6ulRxYO42ffpB303C3BtALME9ncIPEiU9hh+9XO/lIlOtl/HidtW9BRROe5qKaeRciShrQu5u9n6Sxe9SDp3KuzVnEqpB5RxS5sQg65qlwTZSyanZGZgs/jcHjooqJ9L3NBdtkyzh9Mh/M4rK7G5RHA0qSWe71nbdyyzBbOTebras1S3Ov/fzH5+8WhRVgPsw+lEYPKayv8nrC0nnWhqOO51Sl4rXf3UHgJgUfY5YpGJZk7m+HEPYImWMoHu+BxzW84RRvBlhrdLxiSp7CNBWClBuzjNTTsaKihACUbvQODpWk/Ce0uP8JpG7NnWgzSeqBTEqrhtx/ccNdhMqJI5kgMxqw9nLZPStWPFK9tbyWX8r55s/gq/UjryJzTvwEjyHam4VUFj09RdPdzmtdrHeBQ6AjkGrLTJb85rmdfsBtY67EsUvdtvWP7th7qA3hw6GpBurp5PaoOeNRFqRnRRL7wps3OogbXpXAYoEAU/zKCHR2jYyvaELFKn5xNgo5
    username: AgAyqHjUxOGV2fBCg0jq9ZUccOKIYTLIe+1OhpgNjGhOcWZfUg40m1rvGHtczlWwOEuYcU+/URL0OMHe3lwQI8zETxQVWEE6Aj80RvSr3eK16DuklJ1+KW4KvsCvUnIqxlEGfSQgwmrzbudyruH92uJFef2jJIjocVikVAmD2gNgYYikbaUOc1UulSopxzRysu/+xIFwTH5vmC8oYdKLg91r153rjPRfDVGxUlKK93W7gMAZmf8pZ81iFT6Qbu4Z0F3/DqCeq+auC4MmtpBwOlS056wcOuVJ5IjrX06nC0dm5OXesL84wBTyUcceo97YFxw8pY/bTqUVjusmzCK862y4NXhtb2qCLodMbGDUCu5qJ7JeIvLQxxpoWEQjBsIPjtzomMnFlEWvborsg//OenDDIeDcWUTrWn5l8H0t52x6o518+JbUYAt83PUbqJk096Bvq+tFWEPm105S4HRzUsJjG1pJsVpV3Zt2IAp4tVab81iDL6Skb65HhwO7S9KmLACKZ0WU/BtBgfSyPaYjSFqlizINyXy313ZhSOdUbUHqFRszZ+qUQS+ntxmdCfcnp0XHD88CYghHRBj3dD7JDw/xLVSiVl6/R+/ZO144IZjd+3LxOMF4sj8z5GbV3bYosNrLFh8w5KJL82mteyofX1694WTO0L2Cq8wxV6D3aHjjnzjAKInZDe/DPK4hfvV6+LJVk69QD3QVCEW/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

