apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBh2kA8zn2YNzdq/jYQczW+cspNdeSyQhA21QlILWlyz/aYASu2NQTKaFbWRR2J6DenvfET2SDdWzuSNVHvqw8gyJgRc7bZZfvSLnGvWBgXyfWjsv0dhPTsDQS5f3jMROwAO9f39/RALguCeewCZVZLE8IYteJZqGyRBorrBoZS5W8xWzM80Vsvpg5co7N/siueyM6FyBFer4uochxGYiusRWLmyphzzV5qOYW9U6YFIjb1w7SMCHl/pLhIFhabaqE7yHaCzJl7cjh0cPmaB0vEuOcWH7mIrxK9pUVI9gtGcfcaMVZMRj+vyrN0uMyqmnatD0Pns3gx1CVpLr6zPWi5xQzIGL8yzopAgPKuhhKLjRyqTofKuee8FNaXVpOPV+j9/CJC61Fg0sLvDxqVDNrVFbdl6J5rk6Q3C6EXIpya2WO8AHYEAlnF+VgCYwPj5J0CU+bTrMdATMERXK3Q6lH6lUHOQ42S8B+IxeXi6x4gvY9bo3jzswv7SX/BHJftiOcy4CBNbyz5/iWfJeQMcpYd8Bekd2ZTw54BcPZ0EbKeM60ZexoXk2Dnhn7qSQLqCjnNgV0x/XxRgEbbTZZEz1835k6PLZRHmIUqBGUYhKPmYnWtMT8NhH189v8U5Lc6i69gOxrvxaGkV9fW8HstRolM9R8JMODEJOGXHNGQuHsrlWmMvQnrx3GERp4vC3U44F//nLagj/g4NdsJYvi8SoIcphIpB+PO1DCrgN4XHR89DG5OxRWS8J8t8VtOVUMRH4CWek8lKNuaavMv6if0qYX8dZUBaS2H3z7y6uGD+Kz2msPh1dRnM1zskqo5LeC/rhIxiSndeOLXsXZJIgGcv0khJzIIS/24aRmNx142XtUN2Ii/561dENiKr2zkUttv0Z95XridES94ZkJAU9LO4rICX7jAiajiGeC2eQ4LPSfP0w==
    IBM_ENTITLED_REGISTRY_USER: AgAhkpBI0HKFa1j5H9slwlRpI1JDQp/TY+T6WhrVVi4x7Cw1dPGKCg1mqJ7vw/aUeAvVGlSPQU2EXbJu1lwJxhN1ypvY3tkLgPDKaqUe1weZFC2S/VuB7sVnxOFZn2lKBi+YNnF2flCP5arWiEO4fhwa8VSx6n0oIKr6PVOXalbbtVXLvoOGCMySqoLXIL99/aomG8NxyJ4G8y8/nTBtvI2n6Ox5x74ZQ+Tk6RdlrRpeUFZLuiZlupGQ8A8yYBQ8338oM2i7m6kVwaj2xjolSEvBg4HJPKUtUw5K9Kb2sZrn2DttXqpfTRp4/4nsum5vf00jfJRLKe8WNKoIt+OmWaNowGXx28M8pEtfOlQknQC/fcd6bR0TqlwsqqK1J19j/JN4QkxN3NDnYHEx2eCIp3Hl38Ip9y9zpPrIMLQwZAhesUCCqp3+YP764SlUb5o33/0jO8WT42xCclwa9tACcftuA6rin06O+EmpXFXjBqPFFBRM2h2gZMx3CA9JuzR6NhrASUuMK4/2Y1R5oi8pQp+8Xjm8yYkzIJxlXfJDij+uVIP229F/3FHi9rCbLWvruoTAUbNRvVIYcUhxPMc1ykp50iJcUMloWgFFsv0W12KCDV9ZdWz3abs0Np0SokVPQwyF3FWsmQJBU4b0Nu2/JUcn6nSb1JPfwc+K7SZK9SKjfY3TqRLlFDb3M0SFblmXASY1Vg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci
    type: Opaque

